interface RecommendationCardProps {
  recommendation: string;
  confidence: number;
  evidenceCompleteness: number;
}

export default function RecommendationCard({
  recommendation,
  confidence,
  evidenceCompleteness,
}: RecommendationCardProps) {
  const title =
    recommendation ===
    "RESEARCH_FURTHER"
      ? "Research Further"
      : recommendation === "PASS"
      ? "Pass"
      : "Insufficient Evidence";

  const accent =
    recommendation ===
    "RESEARCH_FURTHER"
      ? "#2563EB"
      : recommendation === "PASS"
      ? "#EF4444"
      : "#F59E0B";

  return (
    <section
      style={{
        background:
          "rgba(255,255,255,0.04)",
        backdropFilter: "blur(20px)",
        border:
          "1px solid rgba(255,255,255,0.08)",
        borderRadius: "24px",
        padding: "36px",
        display: "flex",
        justifyContent:
          "space-between",
        alignItems: "flex-start",
        gap: "48px",
        flexWrap: "wrap",
        boxShadow:
          "0 24px 60px rgba(0,0,0,.25)",
      }}
    >
      <div
        style={{
          flex: 1,
          minWidth: "420px",
        }}
      >
        <div
          style={{
            display: "inline-block",
            padding: "8px 14px",
            borderRadius: "999px",
            background:
              "rgba(37,99,235,.15)",
            border:
              "1px solid rgba(37,99,235,.25)",
            color: "#93C5FD",
            fontSize: "13px",
            fontWeight: 600,
            marginBottom: "20px",
          }}
        >
          AI INVESTMENT ANALYSIS
        </div>

        <h2
          style={{
            margin: 0,
            fontSize: "42px",
            fontWeight: 700,
            color: accent,
            letterSpacing: "-1px",
          }}
        >
          {title}
        </h2>

        <p
          style={{
            marginTop: "18px",
            marginBottom: 0,
            maxWidth: "620px",
            color: "#A1A1AA",
            lineHeight: 1.9,
            fontSize: "16px",
          }}
        >
          This recommendation is
          generated by EquiLens AI
          after evaluating financial
          statements, company
          fundamentals, competitor
          intelligence and recent
          market developments. It is
          intended to support
          evidence-based investment
          research and should not be
          interpreted as financial
          advice.
        </p>
      </div>

      <div
        style={{
          width: "340px",
          display: "flex",
          flexDirection: "column",
          gap: "30px",
        }}
      >
        <Metric
          title="Evidence Completeness"
          value={
            evidenceCompleteness
          }
          color="#10B981"
        />

        <Metric
          title="AI Confidence"
          value={confidence}
          color={accent}
        />
      </div>
    </section>
  );
}

interface MetricProps {
  title: string;
  value: number;
  color: string;
}

function Metric({
  title,
  value,
  color,
}: MetricProps) {
  return (
    <div>
      <div
        style={{
          display: "flex",
          justifyContent:
            "space-between",
          marginBottom: "10px",
        }}
      >
        <span
          style={{
            color: "#D4D4D8",
            fontWeight: 500,
          }}
        >
          {title}
        </span>

        <span
          style={{
            color: "#FAFAFA",
            fontWeight: 700,
          }}
        >
          {value}%
        </span>
      </div>

      <div
        style={{
          width: "100%",
          height: "10px",
          background:
            "rgba(255,255,255,.08)",
          borderRadius: "999px",
          overflow: "hidden",
        }}
      >
        <div
          style={{
            width: `${value}%`,
            height: "100%",
            background: color,
            borderRadius: "999px",
          }}
        />
      </div>
    </div>
  );
}